resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '*/5 * * * *'     # Every 5 minutes

  - name: frogbotGitRepo
    type: GitRepo
    configuration:
      gitProvider: gitIntegration
      path: {{.jfrog-pipelines.sourceRepository}}
      branches:
        include: ^{{gitBranch}}$
      cloneProtocol: https

pipelines:
  - name: Frogbot
    steps:
      - name: Frogbot_Scan
        type: Bash # For Windows runner: PowerShell
        configuration:
          integrations:
            - name: jfrogPlatform
            - name: gitIntegration
        inputResources:
          - name: cron_trigger
          - name: frogbotGitRepo
        runtime:
          type: image
          image:
            auto:
              language: node
              version: "16"
        environmentVariables:

          # [Mandatory]
          # JFrog platform URL
          JF_URL: $int_jfrogPlatform_url

          # [Mandatory if JF_USER and JF_PASSWORD are not provided]
          # JFrog access token with 'read' permissions for Xray
          JF_ACCESS_TOKEN: $int_jfrogPlatform_accessToken

          # [Mandatory for Bitbucket]
          # Username of the git provider account
          JF_GIT_USERNAME: ""

          # [Mandatory]
          # Git provider access token with minimal permissions according to the relevant integration type.
          # Read more - https://www.jfrog.com/confluence/display/JFROG/Pipelines+Integrations
          JF_GIT_TOKEN: $int_gitIntegration_token

          # [Mandatory]
          # Name of your git provider: "bitbucketServer" or "github".
          JF_GIT_PROVIDER: ""

          # [Mandatory]
          # API endpoint to your git provider
          JF_GIT_API_ENDPOINT: $int_gitIntegration_url

          # [Mandatory]
          # Git provider project owner.
          JF_GIT_OWNER: ""

          # [Optional]
          # If the machine that runs Frogbot has no access to the internat, set the name of a remote repository
          # in Artifactory, which proxies https://releases.jfrog.io/artifactory
          # The 'frogbot' executable and other tools it needs will be downloaded through this repository.
          # JF_RELEASES_REPO: ""




          ##########################################################################
          ##   If your project uses a 'frogbot-config.yml' file, you can define   ##
          ##   the following variables inside the file, instead of here.          ##
          ##########################################################################

          # [Mandatory if the `installCommand` variable isn't set in your frogbot-config.yml file]
          # The command that installs the project dependencies
          # JF_INSTALL_DEPS_CMD: ""

          # [Optional, default: "."]
          # Relative path to the root of the project in the Git repository
          # JF_WORKING_DIR: path/to/project/dir

          # [Optional]
          # Xray Watches. Learn more about them here: https://www.jfrog.com/confluence/display/JFROG/Configuring+Xray+Watches
          # JF_WATCHES: <watch-1>,<watch-2>...<watch-n>

          # [Optional]
          # JFrog project. Learn more about it here: https://www.jfrog.com/confluence/display/JFROG/Projects
          # JF_PROJECT: <project-key>

          # [Optional, default: "FALSE"]
          # Displays all existing vulnerabilities, including the ones that were added by the pull request.
          # JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"

          # [Optional, default: "TRUE"]
          # Fails the Frogbot task if any security issue is found.
          # JF_FAIL: "FALSE"

          # [Optional]
          # Frogbot will download the project dependencies if they're not cached locally. To download the
          # dependencies from a virtual repository in Artifactory, set the name of of the repository. There's no
          # need to set this value, if it is set in the frogbot-config.yml file.
          # JF_DEPS_REPO: ""

    execution:
      onExecute:
        - cd $res_frogbotGitRepo_resourcePath
        - npm install -g yarn
        - yarn set version berry
        - curl -fLg "https://releases.jfrog.io/artifactory/frogbot/v2/[RELEASE]/getFrogbot.sh" | sh
        - ./frogbot scan-pull-requests
        - ./frogbot scan-and-fix-repos
        # For Windows runner:
        # - iwr https://releases.jfrog.io/artifactory/frogbot/v2/[RELEASE]/frogbot-windows-amd64/frogbot.exe -OutFile .\frogbot.exe
        # - .\frogbot.exe scan-pull-requests
        # - .\frogbot.exe scan-and-fix-repos
