name: Validate Pull Request Target Branch

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  validate-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check Target Branch
        run: |
          if [ "${{ github.base_ref }}" != "main" ] && [ "${{ github.base_ref }}" != "v2_main" ]; then
            echo "Pull requests must target the 'main' or 'v2_main' branch."
            exit 1
          fi
